// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABh6tVuqT64Waht-5AbNztHN_EZo8xXfg',
    appId: '1:17224663133:web:993a2248f55ae8df628db4',
    messagingSenderId: '17224663133',
    projectId: 'fir-prueba-d6c09',
    authDomain: 'fir-prueba-d6c09.firebaseapp.com',
    databaseURL: 'https://fir-prueba-d6c09-default-rtdb.firebaseio.com',
    storageBucket: 'fir-prueba-d6c09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBux0UwmgQZz1B-WKodOQ0CK84bO5mGoGY',
    appId: '1:17224663133:android:83a96ba8b6bab36f628db4',
    messagingSenderId: '17224663133',
    projectId: 'fir-prueba-d6c09',
    databaseURL: 'https://fir-prueba-d6c09-default-rtdb.firebaseio.com',
    storageBucket: 'fir-prueba-d6c09.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCauX4Zq2-o9ATZ49Yev3Ml4RHcXiGWuPg',
    appId: '1:17224663133:web:ea04aca40c54e7a1628db4',
    messagingSenderId: '17224663133',
    projectId: 'fir-prueba-d6c09',
    authDomain: 'fir-prueba-d6c09.firebaseapp.com',
    databaseURL: 'https://fir-prueba-d6c09-default-rtdb.firebaseio.com',
    storageBucket: 'fir-prueba-d6c09.appspot.com',
  );

}